### ISSUE TITLE
Generic RDF, RDF generation when there aren't instances

### ISSUE THREAD

**Issue by EmidioStani** [sparna-git/xls2rdf#35]
Hello @tfrancart ,

I wanted use your tool to generate generic RDF.

I take the example 4 and I remove lines below the URI (the instances) in the sheet Locations, because for me these are optional, it still generates:

schema:Place a skos:ConceptScheme .

So to make it consistent, I am obliged to overwrite it by adding metadata in header (like rdf:type rdfs:Class) despite in A1 I have "Class URI", is this the expected behaviour ?

Would it be possible to generate nothing as I don't have instances ?

**Comment by tfrancart** [comment]
Yes, use the option to avoid SKOS-specific post-processings. This is here in the web UI : 

![image](https://user-images.githubusercontent.com/2728945/166220158-2ae9f0ad-01dd-4d03-9f0e-cb5ccfab664a.png)

And this is option `-np` in command line (see https://github.com/sparna-git/xls2rdf/wiki/Command-line-Excel-to-RDF-conversion)

**Comment by EmidioStani** [comment]
Thanks! that is what I needed
